version: 1
services:
  - type: web
    name: google-sheets-api
    runtime: docker
    repo: https://github.com/BatmanAyush/google-integration
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    dockerCommand: java -Dserver.port=$PORT -jar app.jar
    envVars:
      - key: PORT
        value: 8080
